### ISSUE TITLE
UE5 plugin unavaliable

### ISSUE THREAD

**Issue by 42kam1** [AutoSizeComments/AutoSizeComments#25]
after today's update plugin shows as if installed to engine, but does not appear inside plugin section. Used to work just fine before the update.

**Comment by fpwong** [comment]
Hi yes, the plugin from the marketplace is currently not working. I have submitted a fix which should be out soon. For now please grab the plugin from here: 

https://github.com/fpwong/AutoSizeComments/releases/tag/3.1.4

**Comment by leetNightshade** [comment]
@fpwong is this supposed to be working now? I'm on 3.1.4 but I'm seeing this:
![Uploading image.png…]()

Same issue for AutoSizeComments and BlueprintAssist on custom UE5 engine; idk if that's our problem or plugin's.
