### ISSUE TITLE
Splitting/recombining struct pins doesn't trigger resize

### ISSUE THREAD

**Issue by sbseltzer** [AutoSizeComments/AutoSizeComments#31]
Splitting/recombining a struct pin changes the height of nodes but comments don't resize when splitting or recombining struct pins.

**Comment by fpwong** [comment]
Thanks for letting me know, this was a much bigger issue. Hopefully should be fixed now https://github.com/AutoSizeComments/AutoSizeComments/commit/81931244277fd69ba939b4b22428406c31b4237d
