### ISSUE TITLE
Comment bubble is gone on 3.2.1

### ISSUE THREAD

**Issue by chaixshot** [AutoSizeComments/AutoSizeComments#36]
With default setting.
![image](https://github.com/AutoSizeComments/AutoSizeComments/assets/13221018/b278a718-bd77-419c-969b-0e8683daae75)

**Comment by fpwong** [comment]
Hi, this seems to be a side effect of the new feature I added. You can disable the setting `Use Max Detail Nodes`. I'll see if I can find a workaround so this doesn't happen while the setting is enabled.

**Comment by chaixshot** [comment]
BTW, when create new comment box by default i can change title name but after update i need to press f2 to change title.
Look like it refresh all graph.

**Comment by fpwong** [comment]
This bug should be fixed in 3.2.2: https://github.com/AutoSizeComments/AutoSizeComments/releases/tag/3.2.2
