### ISSUE TITLE
Error adding the plugin to source build of Unreal.

### ISSUE THREAD

**Issue by geekrelief** [AutoSizeComments/AutoSizeComments#38]
Building UE from source (main branch), I added the plugin to /Engine/Plugins/Marketplace, regenerated my solution and built.

I got an error in AutoSizeCommentsStyle.cpp saying `ASC_UE_VERSION_OR_LATER` is undefined.

I added "AutoSizesCommentsMacros.h" to the file to get passed the error. 

I don't see any other references to the macro, so I'm not sure how this would have compiled.

**Comment by fpwong** [comment]
Thanks for letting me know, added in https://github.com/AutoSizeComments/AutoSizeComments/commit/56a290e0432f5cd68420663ca3108e5a2a0c3a42. 

So it seems if a macro can't be found, it will simply be evaluted to 0 which is why it was able to compile
Seems very unsafe.... I wonder if there is a way to disable this behaviour 🤔

**Comment by geekrelief** [comment]
> Thanks for letting me know, added in [56a290e](https://github.com/AutoSizeComments/AutoSizeComments/commit/56a290e0432f5cd68420663ca3108e5a2a0c3a42).
> 
> So it seems if a macro can't be found, it will simply be evaluted to 0 which is why it was able to compile Seems very unsafe.... I wonder if there is a way to disable this behaviour 🤔

What compiler are you using? I think I have the latest version of Visual Studio, and compiling against the source build of Unreal it did pop-up as an error otherwise it would have compiled. So maybe you're missing some flag that elevates the warnings to errors?

**Comment by fpwong** [comment]
Tested with the updated VS and did not make any difference for me.

I think it probably because you are on the main branch that some compiler options have changed.

From this thread https://forums.unrealengine.com/t/warning-level-4/333742/6

> Since we use a custom build system (UBT) a lot of the default VS compiler behavior has been overridden to work with the code. The WindowsPlatformCompilerSetup.h is where various compiler warnings/errors have custom settings to allow VS to work smoothly with the engine. You can edit the settings in this file however you may also need to remove unused variables within the codebase to get it running. If you are able to do so then you may want to submit a pull request to make it easier to use these settings in the future.
