### ISSUE TITLE
New comment does not focus on rename

### ISSUE THREAD

**Issue by nado** [AutoSizeComments/AutoSizeComments#39]
Hi,

I’ve encountered a bug where newly added comments require me to manually rename them (F2) instead of having the focus on the text edition automatically while `bAutoRenameNewComments` is set to true.

While investigating, I found that the `CommentToASCMapping` did not contain the newly created comment node GUID resulting in this code never entering in the if block.
```cpp
if (TSharedPtr<SAutoSizeCommentsGraphNode> ASCComment = FASCState::Get().GetASCComment(NewComment))
{
	ASCComment->RequestRename();
}
```
https://github.com/AutoSizeComments/AutoSizeComments/blob/866a5a0e0707749840f1bf70b63889a98f67326a/Source/AutoSizeComments/Private/AutoSizeCommentsGraphHandler.cpp#L782

I am using ue 4.27.2 source, plugin 3.2.3.

**Comment by fpwong** [comment]
Hmm it does appear this function is not being called. I don't quite remember why this was required because the renaming seems to work for me on 5.3 and 4.27.

If you breakpoint inside `SGraphNode::RequestRename` it should be called in the engine when added to the graph from `SGraphPanel::AddNode`.

```c++
        if (bWasUserAdded)
	{
		// Add the node to visible children, this allows focus to occur on sub-widgets for naming purposes.
		VisibleChildren.Add(NewNode.ToSharedRef());

		NewNode->PlaySpawnEffect();
		NewNode->RequestRenameOnSpawn();
	}
```

Can you check if this is working for you? Also check if a new CustomEvent node is being auto renamed correctly, cause it should be using the same flow to do so.

**Comment by nado** [comment]
I added the breakpoint and never went into the `SGraphNode::RequestRename` function, the custom event added prompted me for renaming on spawn and the name was applied effectively, same for the replicated rename (Client/Server/Multicast), they were working fine on a custom event.

When breaking on the `NewNode->RequestRenameOnSpawn()` I went it the following call stack (both for comment which didnt work and for the custom event which did).

![image](https://github.com/AutoSizeComments/AutoSizeComments/assets/750258/b3e52b3b-9b84-4fce-8ef2-195054683c12)

**Comment by fpwong** [comment]
I'm really not sure how this can happen. Looking at UEdGraphNode_Comment, in the constructor it sets bCanRenameNode to true. Is this somehow false only when the node is created? Because otherwise it wouldn't ever let you rename if bCanRenameNode is always false.

So if you double click on the comment node title, does it let you rename? When you double click it should call RequestRename as part of my comment node logic in `SAutoSizeCommentsGraphNode::OnMouseButtonDoubleClick`.

There is one other class which inherits from UEdGraphNode_Comment, UMaterialGraphNode_Comment but this doesn't set bCanRenameNode to false either 🤔 Just to make sure, this is happening on a regular blueprint graph right?

**Comment by nado** [comment]
Double clicking lets me rename the comment as expected, in a regular BP graph yes.

**Comment by fpwong** [comment]
Thanks for letting me know and sorry for the lack of replies. I was on holidays and forgot about this issue :/

My guess would be you have a setting change on your project? If you are sharing the settings between your team usiing a `DefaultEditorPerProjectUserSettings.ini`, please send me this and I can test it again for you.

If not, then it would be unlikely that both you and your colleague are running into the same bug.

However if you would like to try resetting your plugin settings, you can by going to:

> %Project%/Saved/Config/WindowsEditor/EditorPerProjectUserSettings.ini

and searching in here for `[/Script/AutoSizeComments.AutoSizeCommentsSettings]`

By deleting the lines in this section, you can resetting the plugin back to default. Of course, make sure to keep a backup before you do this :)

---

It could perhaps be a plugin or your custom engine change interfering but I think that is more unlikely.

**Comment by nado** [comment]
Indeed the settings were at fault.

When setting `bEnableCommentBubbleDefaults=False` the issue is gone, I’ll settle with the absence of bubble by default for now, comment renaming is way more important.

My complete ASC section in the project repository:
```ini
[/Script/AutoSizeComments.AutoSizeCommentsSettings]
DefaultFontSize=18
bUseDefaultFontSize=False
DefaultCommentColorMethod=Default
DefaultCommentColor=(R=1.000000,G=1.000000,B=1.000000,A=1.000000)
bAggressivelyUseDefaultColor=False
bUseRandomColorFromList=False
HeaderStyle=(Color=(R=0.500000,G=0.500000,B=0.500000,A=1.000000),FontSize=18,bSetHeader=False)
+PresetStyles=(Color=(R=1.000000,G=1.000000,B=1.000000,A=1.000000),FontSize=18,bSetHeader=False)
+PresetStyles=(Color=(R=1.000000,G=1.000000,B=0.100000,A=1.000000),FontSize=18,bSetHeader=False)
TaggedPresets=(("TODO:", (Color=(R=0.000000,G=1.000000,B=1.000000,A=1.000000))),("TOCLEAN:", (Color=(R=1.000000,G=0.000000,B=0.000000,A=1.000000))),("DEPRECATED:", (Color=(R=0.000000,G=0.000000,B=1.000000,A=1.000000),bSetHeader=True)),("DEV:", (Color=(R=0.000000,G=1.000000,B=0.000000,A=1.000000))),("PROTO:", (Color=(R=1.000000,G=0.500000,B=0.000000,A=1.000000))))
bHideCommentBubble=False
bEnableCommentBubbleDefaults=True
bDefaultShowBubbleWhenZoomed=True
bSnapToGridWhileResizing=True
bHideRandomizeButton=True
```

**Comment by fpwong** [comment]
Thanks for letting me know. I can confirm something odd is going on with the `bEnableCommentBubbleDefaults`. Not immediately obvious what is causing this but I'll hopefully get this sorted out soon.

**Comment by nado** [comment]
Feel free to ping me here or on discord (nado1764) should you need any additional environment details to recreate the bug or to try a fix on my setup.
Thanks for your work and your plugin
